# -*- coding: utf-8 -*-
"""Day 3 Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHUy2EQLoZuespKcqyyBEY2TPYbysfi4
"""

def greet():
  print("Hello,welcome to the internship!")
greet()

"""**Arguments**"""

def add_numbers(a,b):
  return a+b
result=add_numbers(5,3)
print(result)

"""**Global vatiable**"""

x=10
def show_value():
  x=5
show_value()
print(x)

"""**Scope of variable**"""

icecream="venilla"
def food():
  vegetable="potato"
  fruit="lichi"
  print(vegetable+" is a local variable value.")
  print(icecream+" is a global variable value.")
  print(fruit+" is a local variable value.")
food()

"""Global variable(global scope)"""

icecream="venilla"
def food():
  vegetable="potato"
  fruit="lichi"
  print(vegetable+" is a local variable value")
food()
print(icecream+" is a global variable value")
#print(fruit+"is a local variable value")

"""**Modules**"""

import math
import random

print(math.sqrt(16))
print(random.randint(1,10))

import math
import random

colors = ["Red", "Blue", "Green", "Yellow"]

print(math.sqrt(16))
print(random.choice(colors))

import math
import random
print(math.factorial(5))
print(random.choice([10,20,30,40]))

import random
print(random.randrange(1,20))

import random
print(random.random())

import random
print(random.uniform(1.5,5.5))

import random
numbers=[1,2,3,4,5]
random.shuffle(numbers) 
print(numbers)

import random
fruits=["Apple","Banana","Mango","Orange"]
print(random.sample(fruits,2))

