# -*- coding: utf-8 -*-
"""Day 2 Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8CNx8cDG1wlQjscwJyuiLkTTxoRvzSv

List example
"""

numbers=[10,20,30,40]

"""Tuple example"""

coordinates=(5,10)
coordinates.insert(2,20)
print(numbers)
print(coordinates)

Fruits=["orange",40,10,"apple",50,"watermelon",100]
Fruits[3]

Fruits[3:6]

Fruits[-4:-2]

marks=[85,72,90]
marks.append(88)
print(marks)

marks.pop()
marks.sort()
print(marks)

marks=[10,20,30,40]
marks.insert(2,20)
print(marks)