# -*- coding: utf-8 -*-
"""Day 4 Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0VLgLM5l48nrPCHddRdzxKQ7Phx47rF
"""

import numpy as np
a=np.array(([1,2,3],[4,5,6]))
b=np.array([10,20,30])
result= a+b
print(result)

arr=np.random.rand(1000000)
print(arr)
squared=arr**2
print(squared)

arr=np.arange(12)
reshaped=arr.reshape(6,2)
print(reshaped)

a=np.array([1,2])
b=np.array([3,4])
vstacked=np.vstack((a,b))
print(vstacked)

a=[1,2,3,3,4,5]
mean=np.mean(a)
print(mean)
median=np.median(a)
print(median)
mode=np.mode(a)
print(mode)

standared deviation and variance

arr=np.arange(0,24,2)
print(arr)
print("shape before reshape",arr.shape)
arr3d=arr.reshape(3,2,2)
print("shape after reshape",arr3d.shape)
print(arr3d)

"""**Linspace**"""

arr=np.linspace(0,1,6)
print(arr)

arr=np.random.uniform(10,20,size=(2,2)) #uniform means for decimal
print(arr)

"""**Data type**"""

arr=np.array([1,2])
print(arr.dtype) # data type

a=np.array([10,20,30])
b=np.array([1,2,3])
print("Addition:",a+b)
print("Multiplication by scalar:",a*2)
print("Element wise multiplication:",a*b)
print("Mean of array a:",np.mean(a))

"""**Floor**"""

import numpy as np
arr=np.array((1.2,2.8,-3.7))
print(np.floor(arr))

"""**Ceil**"""

import numpy as np
arr=np.array((1.2,2.8,-3.7))
print(np.ceil(arr))

arr=np.array([1.2,2.8,-3.7])
print("floor:",np.floor(arr))
print("ceil:",np.ceil(arr))
print("trunc:",np.trunc(arr))
print("round:",np.round(arr))